version: '3.7'
services:
  node_app:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "1234:4000"

  react_app:
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    ports:
      - "4321:80"
