name: Build and Publish Binary

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set npm registry
        run: npm config set registry https://registry.npmmirror.com

      - name: Install dependencies
        run: |
          cd Backend
          npm i  --unsafe-perm

      - name: Get the date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Build binary
        run: |
          cd Backend
          npm run build:pkg

      - name: Compress binary file
        run: tar -czvf binary.tar.gz ./Backend/binary/arm64_binary

      - name: Publish binary release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./binary.tar.gz
          asset_name: binary.tar.gz
          asset_content_type: application/gzip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
