name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'Backend/**'
            frontend:
              - 'Frontend/**'

  build-and-push-backend:
    needs: check_changes
    if: needs.check_changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout additional repository
        run: |
          git clone https://x-access-token:${{ secrets.MY_PAT }}@github.com/XindongG/LiveRedirect.git
        working-directory: ./Backend

      - name: Show current directory
        run: |
          pwd
          ls -al
        working-directory: ./Backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: xindongg/backend:${{ github.sha }}

#      - name: update Docker Hub Description
#        uses: peter-evans/dockerhub-description@v3
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#          repository: xindongg/backend
#          short-description: "Commit SHA: ${{ github.sha }}"

  build-and-push-frontend:
    needs: check_changes
    if: needs.check_changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: xindongg/frontend:${{ github.sha }}

