name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Enable Docker Experimental Features
        run: |
          mkdir -p ~/.docker
          echo '{"experimental":true}' | tee ~/.docker/config.json

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: xindongg/backend:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: xindongg/frontend:latest

      - name: Pull, retag and push allinone Docker image for linux/amd64
        run: |
          docker pull --platform linux/amd64 youshandefeiyang/allinone:latest
          docker tag youshandefeiyang/allinone:latest xindongg/allinone:latest-amd64
          docker push xindongg/allinone:latest-amd64

      - name: Pull, retag and push allinone Docker image for linux/arm/v7
        run: |
          docker pull --platform linux/arm/v7 youshandefeiyang/allinone:latest
          docker tag youshandefeiyang/allinone:latest xindongg/allinone:latest-armv7
          docker push xindongg/allinone:latest-armv7

      - name: Pull, retag and push allinone Docker image for linux/arm64
        run: |
          docker pull --platform linux/arm64 youshandefeiyang/allinone:latest
          docker tag youshandefeiyang/allinone:latest xindongg/allinone:latest-arm64
          docker push xindongg/allinone:latest-arm64
