name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build binary file
        run: cd "${{ github.workspace }}/Backend" && npm install && npm i -g pkg && npm run build:pkg

      - name: Compress binary file
        run: tar -czvf "${{ github.workspace }}/Backend/binary/arm64_binary.tar.gz" -C "${{ github.workspace }}/Backend/binary/" arm64_binary

      - name: Upload compressed binary file to Releases
        uses: actions/upload-artifact@v2
        with:
          name: arm64_binary.tar.gz
          path: "${{ github.workspace }}/Backend/binary/arm64_binary.tar.gz"
          description: This package is for use on arm64 systems

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xindongg/backend:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xindongg/frontend:latest
